In [36]:
import numpy as np
from sklearn import preprocessing
import pandas as pd

In [37]:
data = np.genfromtxt(r'C:\Users\JAYANTI VISHNOI\Desktop\ml\0000000000002417_training_boston_x_y_train.csv', delimiter=',')
boston = data
data=np.insert(data,13,1,axis=1) #inserting a column with 1 at a index before 13 ..0 se start h idx
x_train=data[:,:-1]
y_train=data[:,-1]
#data[:,:-1] =  (data[:,:-1] - data[:,:-1].mean())/data[:,:-1].std()
def step_gradient(points, learning_rate, m):
    M = len(points)
    temp=np.zeros((14,1))
    temp=np.asmatrix(temp)
    for i in range(M):
        x = np.asmatrix(points[i, 0:-1]) 
        y = np.asmatrix(points[i, -1])
        #print(x.shape,y.shape,m.shape)
        for j in range(len(m)):
            #print(temp[j].shape)
            #print(((-2/M)* (y - (x * m) )*x[i,j]).shape)
            temp[j]=temp[j] + (-2/M)* (y - (x * m) )*x[0,j] #x vector he e row or 13 columns 
            
    new_m = m - learning_rate*temp
    
    return new_m

In [38]:
def gd(points, learning_rate, num_iterations):
    m = np.zeros((14,1))
    #print(m.shape)
    m=np.asmatrix(m)
    for i in range(num_iterations):
        m = step_gradient(points, learning_rate, m)
        #print(i, " Cost: ", cost(points, m))
    return m

In [39]:
def cost(points, m):
    total_cost = 0
    M = len(points)
    for i in range(M):
        x = np.asmatrix(points[i, 0:-1])
        y = np.asmatrix(points[i, -1])
        #print(((y - x*m)**2).shape)
        total_cost+=((y - x*m)**2)
    return total_cost*(1/M)

In [40]:
learning_rate = 0.001
num_iterations = 400
m = gd(data, learning_rate, num_iterations)
print(m)

[[ -0.61894582]
 [  0.43267629]
 [ -0.48307246]
 [  0.98877609]
 [ -0.40687854]
 [  2.65204787]
 [ -0.04440778]
 [ -0.29686588]
 [  0.13340352]
 [ -0.29350722]
 [ -1.25691435]
 [  0.57713589]
 [ -2.19823233]
 [ 12.47539979]]


In [41]:
def score(y,y_pred):
    a = ((y - y_pred)**2).sum()
    b = ((y - y.mean())**2).sum()
    print(a,b)
    return 1 - a/b
#x_train=data[:,:-1]
#y_train=data[:,-1]
y_pred_train = np.array(np.asmatrix(x_train)*m).reshape(1,-1)
#print((y_pred_train.shape),(x_train.shape),(y_train.shape))
accuracy=score(y_train,y_pred_train)
print("Train data accuracy:",accuracy)

50421.9827661 33326.5458047
Train data accuracy: -0.512967562301


In [42]:
x_test = np.genfromtxt(r'C:\Users\JAYANTI VISHNOI\Desktop\ml\0000000000002417_test_boston_x_test.csv', delimiter=',')
x_test = np.insert(x_test,13,1,axis=1)
x_test = np.asmatrix(x_test)
y_pred = x_test*m


matrix([[  1.09071798],
        [ 17.47302037],
        [ 11.68965335],
        [ 14.72054803],
        [ 11.05484279],
        [ -1.54387434],
        [ 16.81036113],
        [ 13.36569287],
        [  9.615515  ],
        [ 12.36357492],
        [ 14.38574284],
        [  9.66833525],
        [ 12.17196472],
        [ 12.28724781],
        [ 28.55641156],
        [ 14.85728192],
        [ 13.86638981],
        [ 15.54419336],
        [ 12.40378987],
        [ 18.74407392],
        [ 12.79023217],
        [ 12.19924137],
        [ 18.75546235],
        [ 23.15262249],
        [ 21.7765176 ],
        [  5.03125635],
        [ 11.17674134],
        [ 19.51469268],
        [ 14.77942973],
        [ 21.15298755],
        [  9.44945697],
        [ 14.39062201],
        [ 13.24768464],
        [ 15.06524149],
        [  5.91876548],
        [ 16.1009736 ],
        [ 15.4096712 ],
        [ 10.6556459 ],
        [ 14.77070028],
        [  2.43560853],
        [ -2.33624757],
        [ 17.162

In [43]:
np.savetxt('Prediction_Boston.csv',y_pred,fmt='%.8f')

In [44]:
from sklearn.ensemble import GradientBoostingRegressor

In [45]:
clf=GradientBoostingRegressor(n_estimators=20000)
x_test = np.genfromtxt(r'C:\Users\JAYANTI VISHNOI\Desktop\ml\0000000000002417_test_boston_x_test.csv', delimiter=',')
y_train=y_train.reshape(-1,1)
x_train=boston[:,:-1]
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)


C:\Users\JAYANTI VISHNOI\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([ 14.17600881,  27.58418328,  15.18682301,  21.55387841,
        21.56366126,  11.9420963 ,  29.96403668,  25.82205818,
        17.92170635,  22.01385701,  24.79432033,  16.5048471 ,
        19.06332309,  20.52529552,  52.14849999,  20.28228231,
        23.91596129,  21.98985248,  18.20419329,  30.45287398,
        20.64864072,  21.66495169,  36.68436626,  31.05350269,
        33.36783678,  16.62270166,  21.34240036,  31.16025573,
        20.03080524,  28.63142168,  17.53456556,  24.79959218,
        20.09617376,  21.98408037,   8.07574981,  23.91398302,
        23.79396158,  20.73239353,  23.45541503,   8.12525756,
        15.50233542,  22.82592272,  23.88475556,  19.76527712,
        22.67265505,  10.35636721,  43.37750635,  24.25639248,
        35.37464892,  13.37948413,  12.90361221,  46.08261297,
        13.44583998,  20.17677993,  16.07856278,  19.60614275,
        18.66406911,  22.46328815,  13.36310084,  15.60742653,
        12.52110693,  26.77516912,  22.35119237,  23.81

In [46]:
np.savetxt('Prediction_Boston.csv',y_pred,fmt='%0.50f')